// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `value`

/// Enable logging ORT messages to the console
void enableOrtDebugMessages({OrtDebugLevel? level}) =>
    RustLib.instance.api.crateApiDebugEnableOrtDebugMessages(level: level);

/// The level of logging for [enable_ort_debug_messages]
enum OrtDebugLevel { trace, debug, info, warn, error }
